# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Holos < Formula
  desc "Holos CLI"
  homepage "https://holos.run"
  version "0.102.0"

  depends_on "helm" => :optional
  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/holos-run/holos/releases/download/v0.102.0/holos_Darwin_x86_64.tar.gz"
      sha256 "2470f62c344e870496e83547a9e3d46522d81a43bda375f211397980e46f6ec5"

      def install
        bin.install "holos"
        bash_output = Utils.safe_popen_read(bin/"holos", "completion", "bash")
        (bash_completion/"holos").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"holos", "completion", "zsh")
        (zsh_completion/"_holos").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"holos", "completion", "fish")
        (fish_completion/"holos.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/holos-run/holos/releases/download/v0.102.0/holos_Darwin_arm64.tar.gz"
      sha256 "f98e2ec048c16cddca69a1083049644f4c4bbc486fc60a46c49fae4fc02bbe52"

      def install
        bin.install "holos"
        bash_output = Utils.safe_popen_read(bin/"holos", "completion", "bash")
        (bash_completion/"holos").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"holos", "completion", "zsh")
        (zsh_completion/"_holos").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"holos", "completion", "fish")
        (fish_completion/"holos.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/holos-run/holos/releases/download/v0.102.0/holos_Linux_x86_64.tar.gz"
        sha256 "0921834e2def793b1f69f931124eb3638cbd4fb8f3652d0ed16ef2fadb629fde"

        def install
          bin.install "holos"
          bash_output = Utils.safe_popen_read(bin/"holos", "completion", "bash")
          (bash_completion/"holos").write bash_output
          zsh_output = Utils.safe_popen_read(bin/"holos", "completion", "zsh")
          (zsh_completion/"_holos").write zsh_output
          fish_output = Utils.safe_popen_read(bin/"holos", "completion", "fish")
          (fish_completion/"holos.fish").write fish_output
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/holos-run/holos/releases/download/v0.102.0/holos_Linux_arm64.tar.gz"
        sha256 "35067a675b44e9acaedd5f0376bb5b6e70532dd417d03426c9c3afac0db93f02"

        def install
          bin.install "holos"
          bash_output = Utils.safe_popen_read(bin/"holos", "completion", "bash")
          (bash_completion/"holos").write bash_output
          zsh_output = Utils.safe_popen_read(bin/"holos", "completion", "zsh")
          (zsh_completion/"_holos").write zsh_output
          fish_output = Utils.safe_popen_read(bin/"holos", "completion", "fish")
          (fish_completion/"holos.fish").write fish_output
        end
      end
    end
  end

  test do
    system "#{bin}/holos --version"
  end
end
